### ISSUE TITLE
to_decimal() panics on some values

### ISSUE THREAD

**Issue by blueglyph** [dtolnay/dragonbox#3]
## Environment

Last revision on master branch (830d0483bdb048d83b270dd4228e8cf4a31cefbf).

* **Rust toolchain version:** 1.64.0 (a55dd71d5 2022-09-19) x86_64-pc-windows-msvc
* **Operating system:** Windows 10 10.0

## Description

The following value triggers an error:

1.0902420340782359E+57

##  How to reproduce

- `cargo test --package dragonbox --test binary64_test test_regression`
=> OK
- add this test to `test_regression()`
```rust
check!(1.0902420340782359E+57);
```
- `cargo test --package dragonbox --test binary64_test test_regression`
=> panic

> assertion failed: (exp as usize) < TABLE_SIZE
> thread 'test_regression' panicked at 'assertion failed: (exp as usize) < TABLE_SIZE', src\div.rs:71:5
> stack backtrace:
>    0: std::panicking::begin_panic_handler
>              at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\panicking.rs:584
>    1: core::panicking::panic_fmt
>              at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\panicking.rs:142
>    2: core::panicking::panic
>              at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\panicking.rs:48
>    3: dragonbox::div::divisible_by_power_of_5<24>
>              at .\src\div.rs:71
>    4: dragonbox::is_product_integer_fc
>              at .\src\lib.rs:469
>    5: dragonbox::compute_nearest_normal
>              at .\src\lib.rs:325
>    6: dragonbox::to_decimal
>              at .\src\lib.rs:553
>    7: dragonbox::to_chars::to_chars
>              at .\src\to_chars.rs:38
>    8: dragonbox::buffer::impl$5::write_to_dragonbox_buffer
>              at .\src\buffer.rs:112
>    9: dragonbox::Buffer::format_finite<f64>
>              at .\src\buffer.rs:52
>   10: dragonbox::Buffer::format<f64>
>              at .\src\buffer.rs:30
>   11: binary64_test::to_chars
>              at .\tests\binary64_test.rs:35
>   12: binary64_test::test_regression
>              at .\tests\binary64_test.rs:115
>   13: binary64_test::test_regression::closure$0
>              at .\tests\binary64_test.rs:106
>   14: core::ops::function::FnOnce::call_once<binary64_test::test_regression::closure_env$0,tuple$<> >
>              at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52\library\core\src\ops\function.rs:248
>   15: core::ops::function::FnOnce::call_once
>              at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\ops\function.rs:248
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

## Misc

I have changed the Cargo.toml to edition 2021 but I don't think this should have any impact.

I noticed that the original C++ source code has received many updates since the port to Rust, but I'm not sure they're relevant to that particular problem. I currently don't have the tools to check this particular value with the original C++ Dragonbox code, unfortunately; I will post an update if I manage to do that test.

**Comment by blueglyph** [comment]
Other values crashing in the same function:
- 5.3461812015486243E+26
- 2.8674588045599296E+66
- 1.2182856909681335E+77
- 2.0596292913323055E+69
- 1.3331169462028886E+60
- ...

If that helps, it's easy to generate a few random test values with the `oorandom` crate, using a seed:

```rust
    #[test]
    fn test_bin_to_dec_rand() {
        let mut rng = oorandom::Rand64::new(0);
        for _ in 0..100000 {
            let exp = rng.rand_range(0..1022 + 1024) as f64 - 1022.0;
            let mant = rng.rand_float();
            let f = exp.exp() * mant;
            let f_str = display(f, DisplayFormat::Fix, 0, 0);
        }
    }
```

**Comment by blueglyph** [comment]
Actually I had a Manjaro VM I could quickly use to test the first value (1.0902420340782359E+57) with release 1.1.3 of dragonbox and it doesn't show the problem. The expected value comes out of `to_chars<double>` with the 'to_even' policy (I've just added an extra test in `subproject/test/source/test_all_shorter_interval_cases.cpp`).

The problems seems to arise in step 3 of `compute_nearest_normal`, with `if is_product_integer_fc(two_fc, exponent, minus_k)` with exponent=39 and minus_k=39, that ultimately calls `divisible_by_power_of_5()` with that out-of-boundary value of minus_k. I see that the C++ code goes through the same path for that value but the code is quite different, which makes it hard to see where the problem actually is.

**Comment by jk-jeon** [comment]
@blueglyph Just for your information. Version 1.1.3 of the C++ reference implementation no longer relies on `divisible_by_power_of_5()`, in fact there is no `is_product_integer_fc()` anymore. 

Anyway, `exponent=39` cannot yield `minus_k=39`, `minus_k` is supposed to be `9` in that case. I don't think older versions of the reference implementation might have the same problem.

**Comment by blueglyph** [comment]
@jk-jeon Thanks for the feedback! Indeed I couldn't find it in the current version of your code, but I didn't check in the history.

I suspect David may have mainly implemented it then to measure the performance as he did with other algorithms. There are some recent updates however, so I'm not sure whether there's an intention to update the code to match your last changes. Unfortunately I can't try that on my own because I'm not familiar enough with C++ 17, and also by lack of time at the moment.

Perhaps I'm simply misusing this library. I may have a look at this specific problem later by comparing to an older version of the reference but no promise.

**Comment by jk-jeon** [comment]
Like you are not familiar enough with C++17, I'm not familiar enough with Rust so I couldn't test the code in this repo 😂. But I skimmed over the implementation and couldn't spot anything different from my original implementation. As I noted in the previous comment, `minus_k` cannot be `39` when `exponent=39` if things are all correctly written, so with that information maybe the most suspicious place is the implementation of fast log computation stuffs...
